# Header
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  Bridges: /bridges
  About: /knightabout
  Announcement : /announcement
  
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
- nav
- about

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:


# GalMenu - PC端右键调出，移动端长按
# galmenu决定是否开启
# mp3play决定是否开启音效
galmenu: true
mp3play: false
gaymenu_item:
- name: 公告
  url : /announcement
- name: 标签
  url : /tags
- name: 分类
  url : /categories
- name: 归档
  url : /archives
- name: 关于
  url : /knightabout
- name: 传送门
  url : /bridges

# 社交链接
social:
- url: https://github.com/Wldcmzy
  name: Github
- url: https://blog.csdn.net/wldcmzy
  name: CSDN
- url: https://space.bilibili.com/83743701
  name: bilibili(无技术和学习内容)

# 友情链接
# name : url
link_title: 友情链接
links:
  夏娜主题作者的博客: https://shanamaid.github.io/



# Sidebar Avatar
# in theme directory(source/images): /images/avatar.jpg
# in site  directory(source/uploads): /uploads/avatar.jpg
# 头像
avatar: /images/avatar.png


# 网站统计
# 站长统计 填写id
# eg:　
# CNZZ: 123456789
CNZZ: 

# 评论
# 友言uid
uyan: 

# leadcloud访问次数统计
# 
leancloud_visitors:
  enable: false
  app_id: 
  app_key: 